bird irradiance model implementation
tommarek/MPCHomeControl pull request #16
Opened 2022-11-17 21:03 UTC by tommarek

2022-12-11 18:43 UTC, bluecube requested changes
Nasel jsem tam dve jasne chyby pouziti deg vs rad, taky tam mas skoro vsude takove hrozne komplikovane pouziti toho uom.

Moc teda celkove nechapu k cemu je to vsechno dobre, proc je tam tolik zpusobu jak ziskat irradiance a proc je to tak hrozne slozite :)

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +const SOLAR_CONST: f64 = 1367.0; // W/m^2
Lepsi jmeno by bylo lepsi

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +pub fn get_vector_from_azimuth_zenith(azimuth: &Angle, zenith_angle: &Angle) -> Vector3<f64> {
Vic by se mi libilo kdyby tato funkce byla definovana jako `get_vector_from_azimuth_elevation(azimuth, 90-zenith_angle)`

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +pub fn get_effective_illuminated_area(
Neni tato funkce uz zbytecna?  `get_total_irradiance_on_tilted_surface` podle me dela vse na co by se tato funkce dala pouzit. Nebo se pletu?

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +pub fn get_effective_illuminated_area(
Take ma velkou duplikaci s obsahem `get_projection`

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +    sun_vector.dot(&surface_vector).max(0.0)
tady by se melo volat `get_illumination_coefficient`

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +// Get a dot product of the surface normal and the sun vector
Neni to uplne dot product, mas tam ten max. Chtelo by to lepsi popis

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +// * `f64` - ground albido value
albEdo

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +// Returns typical ground albido value for a given month
albEdo

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +pub fn get_typical_albedo(utc: &DateTime<Utc>) -> f64 {
Tohle je nezavisle na pozici? Ty cisla vypadaji prilis vysoke na zimu. Jestli je chapu dobre, tak ty 0.2 znamenaji ze je snih, a to u nas takhle dlouho rozhodne nebyva.

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +        * (216.7 * relative_humidity.get::<percent>() / (100.0 * air_temperature.get::<kelvin>())
Tady muzes pouzit jednotku `ratio` a zbavit se te stovky pod zlomkem.

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +pub fn get_total_precipitable_water(
Odkud je tenhle sileny vyraz? Muzes pridat link? (me prijde prakticke u takovychhle veci psat do komentare i cislo stranky v clanku nebo cislo rovnice, nebo tak)

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +pub fn get_extraterrestrial_radiation(utc: &DateTime<Utc>) -> HeatFluxDensity {
🛸

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +// Source: http://solardat.uoregon.edu/SolarRadiationBasics.html#Ref3
v odkazu je navic to `#Ref3`, myslim

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +pub fn get_extraterrestrial_radiation(utc: &DateTime<Utc>) -> HeatFluxDensity {
Z clanku: "This value varies by ±3% as the earth orbits the sun". Ma vubec smysl tohle pocitat? Nebylo by lepsi tu proste placnout tu prumernou hodnotu?

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +        (2.0 * std::f64::consts::PI / 365.0) * (f64::from(utc.ordinal()) - 1.0),
ten konstruktor mas ve stupnich, ale pouzivas tu `2 * PI` !

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +        (2.0 * std::f64::consts::PI / 365.0) * (f64::from(utc.ordinal()) - 1.0),
datetime ma `ordinal0`, nemusis odecitat jednicku

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +    fn get_sky_diffuse_irradiance_on_tilted_surface(
V tehle funkci porad bojujes proti tomu UOM, to nemusis. Je zbyetcne delat na kazdem miste `.get::<Foo>`, rusis tim tu rozmerovou kontrolu. Nebo to ma nejaky jiny duvod?

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +                * (0.5 * surface_angle.get::<degree>()).sin().powf(3.0);
vytahujes ven z uom stupne, pak delas `f64::sin` v radianech.

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +    fn get_sky_diffuse_irradiance_on_tilted_surface(
Neni to jen v tehle funkci, je to uplne vsude :)

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +    pub diffuse_horizontal_irradiance: HeatFluxDensity,
myslim ze by ty membery nemusely byt `pub`

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +    #[allow(clippy::too_many_arguments)]
clippy ma pravdu, mel bys mit asi nejaky struct s parametrama.

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +    #[allow(clippy::too_many_arguments)]
Odkud se vubec berou?

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +        lat: f64,
Tohle by mel byt angle

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +        lon: f64,
tohle taky

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +        lon: f64,
a nebo dohromady lat/lon v jedne strukture

2022-12-11 18:43 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +        let engerer2_coefficients = match averaging_period.get::<minute>() as u32 {
toto je velmi fuj. Co takhle ten algoritmus zafixovat a jednu periodu?

2023-03-25 12:34 UTC, tommarek commented on MPCHomeControl/src/tools/sun.rs
> +const SOLAR_CONST: f64 = 1367.0; // W/m^2
https://en.wikipedia.org/wiki/Solar_constant

2023-03-25 12:40 UTC, tommarek commented on MPCHomeControl/src/tools/sun.rs
> +pub fn get_effective_illuminated_area(
odstranim

2023-03-25 12:44 UTC, tommarek commented on MPCHomeControl/src/tools/sun.rs
> +pub fn get_vector_from_azimuth_zenith(azimuth: &Angle, zenith_angle: &Angle) -> Vector3<f64> {
hotovo

2023-03-25 12:47 UTC, tommarek commented on MPCHomeControl/src/tools/sun.rs
> +    sun_vector.dot(&surface_vector).max(0.0)
pravda, opraveno :)

2023-03-25 12:50 UTC, tommarek commented on MPCHomeControl/src/tools/sun.rs
> +// Get a dot product of the surface normal and the sun vector
hotovo

2023-03-25 12:52 UTC, tommarek commented on MPCHomeControl/src/tools/sun.rs
> +    #[allow(clippy::too_many_arguments)]
z meteorologickych dat :)

2023-03-25 12:52 UTC, tommarek commented on MPCHomeControl/src/tools/sun.rs
> +        lat: f64,
opraveno

2023-03-25 14:23 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +pub fn get_vector_from_azimuth_zenith(azimuth: &Angle, zenith_angle: &Angle) -> Vector3<f64> {
Ted uz je to zas pouzite jen jednou, skoro je lepsi to pouziti nahradit tim 90-zenith_angle :)... co myslis?

2023-03-25 14:39 UTC, bluecube requested changes

2023-03-25 14:39 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +// Get a coefficient value used for calculating effectively illuminated area
Tohle by mel byt docstring (`///`)

2023-03-25 14:39 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +// Get a coefficient value used for calculating effectively illuminated area
->docstring

2023-03-25 14:39 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +// * `f64` - dot product of the surface normal and the sun vector
tady porad mas ten "dot product", pritom je to spis ten "illumination coefficient"

2023-03-25 14:39 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +// Returns typical ground albido value for a given month
Taky by to mel byt docstring

2023-04-04 13:03 UTC, bluecube reviewed
Mam dve super minor poznamky, pokud se ti nechce tak neni ani jedna z nich potreba. Predpokladam ze to ze nemas indirect ambient light je naschval. Vis jak moc silny ten efekt je, ze se ho nevyplati modelovat?

2023-04-04 13:03 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +        0.803 - 0.340 * cloud_cover.get::<ratio>() - 0.458 * cloud_cover.get::<ratio>().powi(2),
je tady potreba opoustet UOM?

`0.803 - 0.340 * cloud_cover- 0.458 * cloud_cover * cloud_cover,` nefunguje?
Pokud ne, tak co `Ratio::new::<ratio>(0.803) - 0.340 * cloud_cover- 0.458 * cloud_cover * cloud_cover,` ?

2023-04-04 13:03 UTC, bluecube commented on MPCHomeControl/src/tools/sun.rs
> +    surface_angle: Angle,
napadlo me prejmenovat na `surface_angle_from_horizontal`  (nebo from vertical?)

2023-04-04 14:49 UTC, merged